AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

# Regras mais brandas para estudo/treino
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  EnforcedStyle: lf
